### PR TITLE
updated SelectTrackerEvents.C

### PR DESCRIPTION
**Pull request by pkumari**
I have correct the mistake and the script runs well.

### CODE REVIEW

**Comment by ram1123** [comment]
Ok. And What about other comments?

**Comment by pkumari** [comment]
i will do  those also

**Comment by ram1123** [comment]
Hi Priyanka,

I tried to fix the bug in doubleGaus*.C and AlignTracker_Shift.C. And now it seems that it is working.

So, Please verify it.

To get the modified code you have to do the following:
1. git remote add upstream git@github.com:ram1123/FNAL-Beam-Test-Scripts.git
2. git fetch upstream
3. git merge upstream/pkumari-Develop

Then you should have the latest code. Then try to run the  macro SelectTracker_Shift.C for 200 events (say) and test it.  For this you have to change number of events here https://github.com/ram1123/FNAL-Beam-Test-Scripts/blob/pkumari-Develop/AlignTrackers_Shift.C#L104-L105

Let me know if you have any problem.

with regards,
Ram

**Comment by ram1123** [comment]
There is one problem with memory. It is going on adding memory so before your program will complete it will run out of memory.

So, we have to delete objects whatever possible in the program after the use, to get rid of this problem.

**Pull request merged**
